version: "3.9"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - GENERIC_TIMEZONE=Europe/Moscow

      # ==== ВАЖНО для работы по пути /n8n ====
      - N8N_PATH=/n8n
      - N8N_ENDPOINT_WEBHOOK=/n8n/
      - N8N_ENDPOINT_WEBHOOK_TEST=/n8n/
      - WEBHOOK_URL=https://bezzze.ru/n8n/

    volumes:
      - ./n8n_data:/home/node/.n8n

    ports:
      - "5678:5678"   # nginx с хоста будет проксировать сюда

  fastapi:
    build: ./backend   # Папка с Dockerfile FastAPI
    container_name: fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"   # nginx будет проксировать сюда
